CREATE SEQUENCE seq_applicant_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_bookmark_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_file_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_skillhashtag_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_hashtag_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_noti_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_portfolio_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_post_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_reply_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_project_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_report_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_review_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_report_no INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE seq_todo_no INCREMENT BY 1 START WITH 1;


